services:
  db:
    image: postgres:16
    env_file:
      - .env
    restart: on-failure
    ports:
      - "5433:${POSTGRES_PORT}"
    volumes:
       - ./data/db:/var/lib/postgresql/data

  app:
    build: .
    restart: on-failure
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      POSTGRES_HOST: db
    volumes:
      - .:/app
    depends_on:
      - db
